import { useNavigate } from 'react-router-dom';
import { useSEO } from '../../lib/useSEO';
import type { SupportedLocale } from '../../i18n';
import Footer from '../../components/layout/Footer/Footer';
import Sidebar from '../../components/layout/Sidebar/Sidebar';
import Icon from '../../components/shared/Icon/Icon';
import styles from './LegalPage.module.css';

interface Props { locale: SupportedLocale; }

function Content() {
  return (
    <div className={styles.doc}>
      <p className={styles.docEyebrow}>Legal</p>
      <h1 className={styles.docTitle}>Terms &amp; Conditions</h1>
      <p className={styles.docDate}>Last updated: 21 May 2026</p>

      <h2>1. Acceptance of terms</h2>
      <p>
        By accessing or using Fanatic Scores ("the Service", "we", "us"), you agree to be bound
        by these Terms &amp; Conditions. If you do not agree, please do not use the Service.
      </p>

      <h2>2. Description of service</h2>
      <p>
        Fanatic Scores is a free web application that provides live football scores, match results,
        league standings, head-to-head statistics and competition information. No account or
        registration is required to use the Service.
      </p>

      <h2>3. Data accuracy and disclaimers</h2>
      <p>
        Match data is sourced from third-party providers (API-Football / api-sports.io). While we
        take reasonable steps to ensure accuracy, we make no warranty that scores, results or
        statistics are complete, up-to-date or error-free. Do not rely on this Service for
        gambling, trading or any purpose where financial decisions depend on data accuracy.
      </p>
      <p>
        <strong>AI-generated content.</strong> Some pages include a short match-day summary
        generated by an AI language model (Claude by Anthropic). These summaries are produced
        automatically from structured match data and are provided for informational purposes only.
        They may contain errors or omissions. We do not guarantee the accuracy of AI-generated
        content and accept no liability for decisions made in reliance on it.
      </p>
      <p>
        <strong>Fanatic Scores is not affiliated with, endorsed by, or officially connected to
        any football league, club, governing body or broadcaster.</strong> All competition names,
        team names and crests are the property of their respective owners and are used for
        identification purposes only.
      </p>

      <h2>4. Intellectual property</h2>
      <p>
        The Fanatic Scores name, logo, design and original content are the intellectual property
        of Fanatic Scores and may not be reproduced, distributed or used without prior written
        permission. Third-party logos and trademarks remain the property of their respective owners.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Scrape, crawl or systematically download data from the Service.</li>
        <li>Attempt to reverse-engineer, disrupt or compromise the Service.</li>
        <li>Use automated means to access the Service at a rate that impairs its performance.</li>
        <li>Misrepresent your identity or impersonate any person or entity.</li>
      </ul>

      <h2>6. Third-party services</h2>
      <p>
        The Service relies on third-party APIs and infrastructure — including API-Football
        (api-sports.io) for match data, Google Firebase for hosting and database, Google Analytics
        4 for anonymised usage analytics (consent-based), and Anthropic's Claude API for
        AI-generated match summaries — to deliver its features. We are not responsible for the
        availability, accuracy or terms of those services.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by applicable law, Fanatic Scores shall not be liable for
        any indirect, incidental, special, consequential or punitive damages arising from your use
        of, or inability to use, the Service.
      </p>

      <h2>8. Changes to these terms</h2>
      <p>
        We may update these Terms &amp; Conditions at any time. Continued use of the Service after
        changes are posted constitutes acceptance of the revised terms. The date at the top of this
        page indicates when the terms were last updated.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These terms are governed by and construed in accordance with the laws of England and Wales.
        Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these terms, please contact us at{' '}
        <a href="mailto:legal@fanaticscores.com">legal@fanaticscores.com</a>.
      </p>
    </div>
  );
}

export default function TermsPage({ locale }: Props) {
  useSEO({ title: 'Terms of Service', description: 'Read the FanaticScores Terms of Service.', canonical: '/en/terms' });
  const navigate = useNavigate();
  return (
    <>
      <div className={styles.desktopOnly}>
        <div className={styles.desktop}>
          <Sidebar locale={locale} />
          <main className={styles.main}>
            <button className={styles.backBtn} onClick={() => navigate(-1)}>
              <Icon name="chevron-left" size={14} /> Back
            </button>
            <Content />
            <Footer />
          </main>
        </div>
      </div>
      <div className={styles.mobileOnly}>
        <div className={styles.mobScreen}>
          <div className={styles.mobTopBar}>
            <button className={styles.mobBackBtn} onClick={() => navigate(-1)}>
              <Icon name="chevron-left" size={16} /> Back
            </button>
            <span className={styles.mobTopTitle}>Terms &amp; Conditions</span>
          </div>
          <div className={styles.mobContent}><Content /><Footer /></div>
        </div>
      </div>
    </>
  );
}
