import styles from './AIInsight.module.css';
import AISigil from '../AISigil/AISigil';

interface AIInsightProps {
  title?: string;
  body: string;
  /** Show action buttons ("Ask anything" / "Tonight's read") */
  showActions?: boolean;
  className?: string;
}

/** Minimal inline renderer: turns **bold** segments into <strong>. The brief
 *  body is generated by our own prompt (not user input), so this only needs to
 *  handle the markdown we emit — bold labels; paragraph breaks are split below. */
function renderInline(text: string) {
  return text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((part, i) => {
    const m = /^\*\*([^*]+)\*\*$/.exec(part);
    return m ? <strong key={i}>{m[1]}</strong> : <span key={i}>{part}</span>;
  });
}

/**
 * AI Pulse card — orange-tinted card with sparkles header and animated shimmer text.
 */
export default function AIInsight({
  title = 'AI Pulse',
  body,
  showActions = false,
  className,
}: AIInsightProps) {
  return (
    <div className={[styles.root, className].filter(Boolean).join(' ')}>
      <div className={styles.header}>
        <AISigil size={14} />
        <span className={styles.title}>{title}</span>
      </div>
      {body.split(/\n{2,}/).map(s => s.trim()).filter(Boolean).map((para, i) => (
        <p key={i} className={`${styles.body} ai-shimmer`} style={i > 0 ? { marginTop: 8 } : undefined}>
          {renderInline(para)}
        </p>
      ))}
      {showActions && (
        <div className={styles.actions}>
          <button className="fs-btn ghost sm">Ask anything</button>
          <button className="fs-btn ghost sm">Tonight's read</button>
        </div>
      )}
    </div>
  );
}
